env = Environment()

env.Append(CPPFLAGS=['-Wall', '-Werror', '-O3', '--std=c++11'])
p = env.Program('vector-test', 'vector-test.cpp')

com = env.Command('vtest.out', ['vector-test'], './$SOURCE | tee $TARGET')

Default(com)
AlwaysBuild(com)

